#!/usr/bin/env python3
"""
Agent Harness - Git Pre-commit Hook Installer and Runner
"""
import os
import sys
import asyncio

# Reconfigure stdout/stderr to utf-8 to avoid encoding errors on Windows terminal
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

# Make sure we can import support_tools from current directory
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

def install_hook():
    workspace_root = os.path.dirname(os.path.abspath(__file__))
    git_dir = os.path.join(workspace_root, ".git")
    
    if not os.path.isdir(git_dir):
        print(f"\033[91m[Harness Installer] Thất bại: Thư mục {git_dir} không tồn tại.\033[0m")
        print("[Harness Installer] Hãy chắc chắn rằng bạn đang chạy script này từ thư mục gốc của Git repository.")
        sys.exit(1)
        
    hooks_dir = os.path.join(git_dir, "hooks")
    os.makedirs(hooks_dir, exist_ok=True)
    
    hook_path = os.path.join(hooks_dir, "pre-commit")
    
    python_exe = sys.executable.replace("\\", "/")
    script_path = os.path.join(workspace_root, "install_hooks.py").replace("\\", "/")
    
    hook_content = f"""#!/bin/sh
# Agent Harness Pre-commit Hook
# Auto-generated by install_hooks.py

PYTHON_EXE="{python_exe}"
SCRIPT_PATH="{script_path}"

echo ""
echo "=== [Agent Harness] Đang chạy Git Pre-commit Hook..."

if [ -f "$PYTHON_EXE" ]; then
    "$PYTHON_EXE" "$SCRIPT_PATH" --run-hook
    EXIT_CODE=$?
else
    if command -v python3 >/dev/null 2>&1; then
        python3 "$SCRIPT_PATH" --run-hook
        EXIT_CODE=$?
    else
        python "$SCRIPT_PATH" --run-hook
        EXIT_CODE=$?
    fi
fi

if [ $EXIT_CODE -ne 0 ]; then
    echo "=== [Agent Harness] ❌ Commit bị chặn do phát hiện lỗi nghiêm trọng ==="
    echo ""
    exit $EXIT_CODE
fi

exit 0
"""
    
    try:
        with open(hook_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(hook_content)
        
        # Make the hook executable (crucial for Linux/macOS and Git Bash on Windows)
        try:
            os.chmod(hook_path, 0o755)
        except Exception:
            pass
            
        print(f"\033[92m[Harness Installer] Đã cài đặt Git Pre-commit Hook thành công tại: {hook_path}\033[0m")
    except Exception as e:
        print(f"\033[91m[Harness Installer] Lỗi ghi file hook: {e}\033[0m")
        sys.exit(1)

def run_hook():
    # Helper to run async function
    try:
        from support_tools import panel_review
    except ImportError as e:
        print(f"\033[91m[Harness Hook] Lỗi import support_tools: {e}\033[0m")
        sys.exit(1)
        
    try:
        result = asyncio.run(panel_review(staged=True))
    except Exception as e:
        print(f"\033[93m[Harness Hook] ⚠️ panel_review bị lỗi khi thực thi: {e}\033[0m")
        print("\033[93m[Harness Hook] Bỏ qua lỗi và cho phép commit tiếp tục...\033[0m")
        sys.exit(0)
        
    if "error" in result:
        err_msg = result["error"]
        if "Không có thay đổi nào để review" in err_msg or "Không có gì để review" in err_msg:
            print("\033[92m[Harness Hook] ✓ Không có thay đổi staged cần review. Tiếp tục commit.\033[0m")
            sys.exit(0)
        else:
            print(f"\033[93m[Harness Hook] ⚠️ Cảnh báo review: {err_msg}\033[0m")
            # If it's a structural or config error, we don't want to block the commit
            sys.exit(0)
            
    findings = result.get("findings", [])
    blockers = [
        f for f in findings 
        if str(f.get("severity", "")).lower() in ("critical", "high")
    ]
    
    if blockers:
        print("\033[91m======================================================================\033[0m")
        print("\033[91m[Agent Harness] ❌ COMMIT BỊ CHẶN: Phát hiện lỗi nghiêm trọng (Critical/High)!\033[0m")
        print("\033[91m======================================================================\033[0m")
        for idx, f in enumerate(blockers, 1):
            file_name = f.get("file", "N/A")
            line = f.get("line", "N/A")
            severity = str(f.get("severity", "")).upper()
            issue = f.get("issue", "N/A")
            fix = f.get("suggested_fix", "N/A")
            print(f"\033[1m[{idx}] {file_name}:{line} - \033[91m{severity}\033[0m")
            print(f"    \033[93mLỗi:\033[0m      {issue}")
            print(f"    \033[92mGợi ý sửa:\033[0m {fix}")
            print()
        print("\033[91mHãy sửa các lỗi trên hoặc bỏ qua hook bằng cách dùng: git commit --no-verify\033[0m")
        print("\033[91mXem báo cáo đầy đủ tại file: REVIEW_REPORT.md\033[0m")
        sys.exit(1)
        
    print("\033[92m[Agent Harness] ✓ Vượt qua bước review pre-commit thành công! (Không phát hiện lỗi Critical/High)\033[0m")
    if findings:
        print(f"[Agent Harness] Lưu ý: Phát hiện {len(findings)} lỗi Medium/Low. Bạn có thể xem chi tiết trong file REVIEW_REPORT.md.")
    sys.exit(0)

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--run-hook":
        run_hook()
    else:
        install_hook()
